version: '3.8'

services:

  iot-gateway:
    build:
      context: ./IoT_gateway
    container_name: iot-gateway
    ports:
      - "50051:50051"
      - "5000:5000"
      - "8766:8765"
    restart: always

  sensor-grpc:
    build:
      context: ./sensors/sensor_1
    container_name: sensor-grpc
    depends_on:
      - iot-gateway
    environment:
      - GATEWAY_HOST=iot-gateway
    restart: always

  sensor-rest:
    build:
      context: ./sensors/sensor_2
    container_name: sensor-rest
    depends_on:
      - iot-gateway
    environment:
      - GATEWAY_HOST=iot-gateway
    restart: always

  sensor-websocket:
    build:
      context: ./sensors/sensor_3
    container_name: sensor-websocket

    restart: always

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=iot_user
      - POSTGRES_PASSWORD=iot_password
      - POSTGRES_DB=health_data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mqtt-subscriber:
    build:
      context: ./mqtt_subscriber
    depends_on:
      - mosquitto
      - postgres
    environment:
      - MQTT_BROKER=mosquitto
      - POSTGRES_HOST=postgres

volumes:
  postgres_data: