version: '3.8'

services:

  iot-gateway:
    build:
      context: ./IoT_gateway
    container_name: iot-gateway
    ports:
      - "50051:50051"
    restart: always

  sensor-grpc:
    build:
      context: ./sensors/sensor_1
    container_name: sensor-grpc
    depends_on:
      - iot-gateway
    environment:
      - GATEWAY_HOST=iot-gateway
    restart: always

  sensor-rest:
    build:
      context: ./sensors/sensor_2
    container_name: sensor-rest
    depends_on:
      - iot-gateway
    environment:
      - GATEWAY_HOST=iot-gateway
    restart: always

  sensor-heartbeat:
    build:
      context: ./sensors/sensor_3
    container_name: sensor-heartbeat

    restart: always